"use strict";
const DB_NAME="satellite-x-mobile", STORE="verification", DB_VERSION=1;
const $=id=>document.getElementById(id);
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:"event_id"});s.createIndex("sync_status","sync_status")}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function put(row){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(row);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
async function all(){const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result.sort((a,b)=>a.queued_at.localeCompare(b.queued_at)));r.onerror=()=>reject(r.error)})}
const hex=buffer=>[...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,"0")).join("");
async function sha256Bytes(bytes){return hex(await crypto.subtle.digest("SHA-256",bytes))}
async function sha256Text(text){return sha256Bytes(new TextEncoder().encode(text))}
function stableStringify(value){if(Array.isArray(value))return `[${value.map(stableStringify).join(",")}]`;if(value&&typeof value==="object")return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stableStringify(value[k])}`).join(",")}}`;return JSON.stringify(value)}
function canonicalEvidence(e){return {captured_at:new Date(e.captured_at).toISOString(),field_id:e.field_id,latitude:Number(e.latitude).toFixed(7),longitude:Number(e.longitude).toFixed(7),notes:e.notes,observation:e.observation,officer_id:e.officer_id,photo_sha256:e.photo_sha256,task_id:e.task_id}}
function base64Bytes(value){return Uint8Array.from(atob(value),c=>c.charCodeAt(0))}
async function verifyReceipt(receipt,row,trustedKey){const a=receipt.signed_artifact;if(!a||a.key_id!==trustedKey.key_id||a.public_key_base64!==trustedKey.public_key_base64)throw new Error("Receipt signing key is not trusted");const receiptPayload={accepted:receipt.accepted,event_id:receipt.event_id,payload_sha256:row.payload_sha256,received_at:receipt.received_at,user_id:row.evidence.officer_id};if(await sha256Text(stableStringify(receiptPayload))!==a.payload_sha256)throw new Error("Receipt payload digest mismatch");const signingPayload={artifact_id:a.artifact_id,artifact_type:a.artifact_type,issued_at:a.issued_at,key_id:a.key_id,parent_sha256:a.parent_sha256,payload_sha256:a.payload_sha256};const key=await crypto.subtle.importKey("raw",base64Bytes(a.public_key_base64),{name:"Ed25519"},false,["verify"]);const ok=await crypto.subtle.verify({name:"Ed25519"},key,base64Bytes(a.signature_base64),new TextEncoder().encode(stableStringify(signingPayload)));if(!ok)throw new Error("Receipt signature is invalid");return true}
function location(){return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve(p.coords),reject,{enableHighAccuracy:true,timeout:30000,maximumAge:0}))}
function status(id,text,warn=false){const e=$(id);e.hidden=false;e.textContent=text;e.className=`status${warn?" warn":""}`}
async function render(){const rows=await all(),queue=$("queue");queue.replaceChildren();if(!rows.length){const empty=document.createElement("p");empty.className="small";empty.textContent="Queue is empty.";queue.append(empty);return}for(const row of rows){const item=document.createElement("div"),title=document.createElement("b"),meta=document.createElement("span"),code=document.createElement("code");item.className="item";title.textContent=`${row.evidence.field_id} · ${row.evidence.observation}`;meta.className="small";meta.textContent=`${row.sync_status} · ${row.queued_at}`;code.textContent=row.event_id;item.append(title,document.createElement("br"),meta,document.createElement("br"),code);queue.append(item)}}
$("sendOtp").addEventListener("click",async()=>{try{const response=await fetch("/api/v1/auth/otp/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:$("officer").value.trim(),phone_e164:$("phone").value.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload.detail||"OTP request failed");$("challenge").value=payload.challenge_id;status("authStatus",`OTP sent to ${payload.masked_phone}; expires ${payload.expires_at}`)}catch(e){status("authStatus",e.message,true)}});
$("verifyOtp").addEventListener("click",async()=>{try{const response=await fetch("/api/v1/auth/otp/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({challenge_id:$("challenge").value,code:$("otpCode").value.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload.detail||"OTP verification failed");$("token").value=payload.token;status("authStatus","Authenticated session created. Token remains only in page memory.")}catch(e){status("authStatus",e.message,true)}});
$("capture").addEventListener("submit",async ev=>{ev.preventDefault();try{status("captureStatus","Reading high-accuracy GPS and hashing photo…");const officer=$("officer").value.trim(),device=$("device").value.trim(),photo=$("photo").files[0];if(!officer||device.length<3||!photo)throw new Error("Officer, device and photo are required");const coords=await location();const photoHash=await sha256Bytes(await photo.arrayBuffer());const now=new Date().toISOString();const evidence={task_id:$("task").value.trim(),field_id:$("field").value.trim(),officer_id:officer,captured_at:now,latitude:coords.latitude,longitude:coords.longitude,observation:$("observation").value,photo_sha256:photoHash,notes:$("notes").value.trim()};const row={event_id:crypto.randomUUID(),device_id:device,queued_at:now,evidence,payload_sha256:await sha256Text(stableStringify(canonicalEvidence(evidence))),photo_blob:photo,sync_status:"pending",server_receipt:null,receipt_verified:false};await put(row);status("captureStatus",`Queued offline. GPS accuracy: ${coords.accuracy.toFixed(1)} m`);ev.target.reset();await render()}catch(e){status("captureStatus",e.message,true)}});
$("sync").addEventListener("click",async()=>{try{const token=$("token").value.trim();if(!token)throw new Error("Authenticated session token is required");const rows=(await all()).filter(r=>r.sync_status==="pending");if(!rows.length){status("syncStatus","Nothing pending.");return}status("syncStatus",`Synchronizing ${rows.length} item(s)…`);const keyResponse=await fetch("/api/v1/security/receipt-key",{cache:"no-store"});if(!keyResponse.ok)throw new Error("Receipt verification key is unavailable");const trustedKey=await keyResponse.json();for(const row of rows){if(!(row.photo_blob instanceof Blob))throw new Error(`Missing offline photo for ${row.event_id}`);const form=new FormData();form.append("expected_sha256",row.evidence.photo_sha256);form.append("photo",row.photo_blob,"evidence-photo");const photoResponse=await fetch(`/api/v1/verification/photo/${encodeURIComponent(row.event_id)}`,{method:"PUT",headers:{"Authorization":`Bearer ${token}`},body:form});if(!photoResponse.ok){const error=await photoResponse.json();throw new Error(error.detail||`Photo upload failed: HTTP ${photoResponse.status}`)}}const response=await fetch("/api/v1/verification/sync",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`},body:JSON.stringify({envelopes:rows.map(({photo_blob,...envelope})=>envelope)})});const payload=await response.json();if(!response.ok)throw new Error(payload.detail||`Sync failed: HTTP ${response.status}`);for(const receipt of payload.receipts){const row=rows.find(x=>x.event_id===receipt.event_id);await verifyReceipt(receipt,row,trustedKey);row.sync_status=receipt.accepted?"synced":"rejected";row.server_receipt=receipt.server_receipt;row.receipt_verified=true;delete row.photo_blob;await put(row)}status("syncStatus",`Synchronized and verified ${payload.receipts.length} item(s).`);await render()}catch(e){status("syncStatus",e.message,true)}});
$("refresh").addEventListener("click",render);
$("officer").value=localStorage.getItem("sx-officer")||"";$("device").value=localStorage.getItem("sx-device")||"FIELD-PHONE-1";
$("officer").addEventListener("change",()=>localStorage.setItem("sx-officer",$("officer").value));$("device").addEventListener("change",()=>localStorage.setItem("sx-device",$("device").value));
if("serviceWorker" in navigator)navigator.serviceWorker.register("/service-worker.js");render();
